name: Deploy to Minikube on Self-Hosted Runner

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner for test

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

 
 
      # Deploy to Minikube
      - name: Deploy application
        run: |
          kubectl apply -f hello-world-deployment.yaml
          kubectl apply -f hello-world-service.yaml
          kubectl apply -f hello-world-ingress.yaml
      - name: Use Minikube IP and NodePort
        run: |
          MINIKUBE_IP=$(minikube ip)
          echo "Access service at http://$MINIKUBE_IP:$NODE_PORT"
          