name: Deploy to Minikube on Self-Hosted Runner

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: Linux  # Use the self-hosted runner for test

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

 
 
      # Deploy to Minikube
      - name: Deploy application
        run: |
          kubectl apply -f hello-world-deployment.yaml
          kubectl apply -f hello-world-service.yaml
          kubectl apply -f hello-world-ingress.yaml